'use client';
import {useEffect,useState} from 'react';
import {gsap} from 'gsap';
import {timelineState} from '@/lib/timeline';
const wa='https://wa.me/5521966027676';
export function HeroScene(){return <section className="scene hero" data-start="0" data-end="1.45"><div className="eyebrow">ESTÚDIO DIGITAL INDEPENDENTE · RIO DE JANEIRO</div><div className="hero-copy"><p className="micro">SITES COM IDENTIDADE PARA<br/>QUEM VIVE DO PRÓPRIO TRABALHO</p><h1>Seu trabalho<br/>já tem valor.<br/><em>Seu site precisa<br/>mostrar isso.</em></h1><p className="intro">Criamos sites para pequenos negócios e profissionais que querem apresentar melhor o próprio trabalho, transmitir confiança e facilitar o contato com seus clientes.</p><a className="text-link magnetic" href="#manifesto">Conhecer a UNDA <span>↗</span></a></div><div className="hero-bottom"><span>DESIGN COM IDENTIDADE</span><span className="scroll-hint">ROLE PARA DESCOBRIR <b>↓</b></span><span>EST. 2026</span></div></section>}
export function ManifestoScene(){return <section className="scene manifesto" data-start="1.45" data-end="4.1"><p className="micro">O QUE UMA BOA PRESENÇA PODE FAZER</p><Manifesto/><div className="manifesto-foot">Não criamos apenas sites.<br/>Criamos a forma como sua marca é percebida.</div></section>}
function Project({className,index,type,title,italic,copy,detail,start,end}:{className:string,index:string,type:string,title:string,italic?:string,copy:React.ReactNode,detail:string,start:number,end:number}){return <section className={`scene project ${className}`} data-start={start} data-end={end}><div className="project-head"><span className="micro">{index} / 04 · {type}</span><span className="micro">DIREÇÃO VISUAL & DESENVOLVIMENTO</span></div><h2>{title} {italic&&<em>{italic}</em>}</h2><div className="project-caption"><p>{copy}</p><span>{detail}</span></div></section>}
export function HandmadeScene(){return <Project className="handmade" index="01" type="PROJETO REAL" title="handmade" italic="by analucia" copy={<>Transformar o feito à mão<br/>em experiência.</>} detail="E-commerce · Artesanal · Editorial" start={4.1} end={5.6}/>}
export function MiraScene(){return <Project className="mira" index="02" type="SITE CONCEITO" title="MIRA" copy={<>Precisão para cuidar.<br/>Naturalidade para sorrir.</>} detail="Clínica odontológica · Rio de Janeiro" start={5.6} end={7.1}/>}
export function BrumaScene(){return <Project className="bruma" index="03" type="SITE CONCEITO" title="BRUMA." copy={<>A casa também<br/>tem memória.</>} detail="Fragrâncias · Matéria · Ritual" start={7.1} end={8.6}/>}
export function OreaScene(){return <Project className="orea" index="04" type="SITE CONCEITO" title="ORÉA" copy={<>Entre o mar,<br/>a mata e o fogo.</>} detail="Restaurante autoral · Santa Teresa" start={8.6} end={10.1}/>}
export function MobileScene(){return <section className="scene mobile-scene" data-start="10.1" data-end="11.1"><p className="micro">FEITO PARA CELULAR</p><h2>Seu cliente<br/>provavelmente<br/>vai chegar <em>por aqui.</em></h2><p>Por isso, mobile não é adaptação.<br/>É parte do projeto desde o início.</p></section>}
export function ServicesScene(){return <section className="scene services" data-start="11.1" data-end="12.45"><p className="micro">PROJETO PERSONALIZADO</p><h2>Um site pensado<br/><em>para o seu negócio.</em></h2><div className="service-list">{['Site institucional','Landing page','Catálogo & portfólio'].map((s,i)=><button key={s} onMouseEnter={()=>timelineState.service=i} onFocus={()=>timelineState.service=i} onClick={()=>timelineState.service=i}><small>0{i+1}</small>{s}<span>↗</span></button>)}</div></section>}
export function PhilosophyScene(){return <section className="scene philosophy" data-start="12.45" data-end="13.25"><p className="micro">NOSSO JEITO DE CRIAR</p><h2>Identidade <em>antes de template.</em><br/>Experiência <em>antes de excesso.</em><br/>Clareza <em>antes de efeito.</em></h2></section>}
export function ProcessScene(){return <section className="scene process" data-start="13.25" data-end="14.2"><p className="micro">ATENDIMENTO PRÓXIMO</p><h2>Do primeiro papo<br/><em>ao site no ar.</em></h2><Process/></section>}
export function AboutScene(){return <section className="scene about" data-start="14.2" data-end="15.05"><p className="micro">SOBRE A UNDA</p><h2>Pequenos negócios<br/>também merecem<br/><em>grandes ideias.</em></h2><div className="about-copy"><p>A UNDA é um estúdio digital que cria sites para pequenos negócios, marcas e profissionais que querem apresentar melhor o próprio trabalho.</p><p>Trabalhamos diretamente em cada projeto, da direção visual ao desenvolvimento.</p></div></section>}
export function ContactScene(){return <section className="scene contact" data-start="15.05" data-end="16.6"><p className="micro">VAMOS COLOCAR SEU TRABALHO NO AR?</p><h2>Seu próximo cliente<br/>vai te procurar.<br/><em>O que ele vai ver?</em></h2><a className="contact-link magnetic" href={wa} target="_blank" rel="noreferrer">Falar com a UNDA. <span>↗</span></a><footer><a className="logo" href="#inicio">UNDA.</a><span>© UNDA 2026</span><a href={wa} target="_blank" rel="noreferrer">Rio de Janeiro ↗</a></footer></section>}
function Manifesto(){const [n,setN]=useState(0);useEffect(()=>{const tick=()=>setN(Math.min(4,Math.max(0,Math.floor((timelineState.progress-1.5)/.49))));gsap.ticker.add(tick);return()=>gsap.ticker.remove(tick)},[]);return <h2 key={n}>{['Não criamos apenas sites.','Criamos presença.','Criamos confiança.','Criamos desejo.',<>Criamos a forma como<br/>sua marca é <em className="percebida">percebida.</em></>][n]}</h2>}
function Process(){const [n,setN]=useState(0);useEffect(()=>{const tick=()=>setN(Math.min(3,Math.max(0,Math.floor((timelineState.progress-13.25)/.23))));gsap.ticker.add(tick);return()=>gsap.ticker.remove(tick)},[]);return <><div className="process-track" style={{'--step':n} as React.CSSProperties}>{['Entender','Criar','Desenvolver','Publicar'].map((x,i)=><div className={i<=n?'active':''} key={x}><small>0{i+1}</small><span>{x}</span></div>)}</div><p className="process-detail">{['Uma conversa para conhecer seu trabalho, seu público e seus objetivos.','Direção visual e conteúdo com a identidade do seu negócio.','Uma experiência rápida, clara e pensada para todos os tamanhos de tela.','Revisão dos detalhes e acompanhamento para colocar seu site no ar.'][n]}</p></>}
