// Reproducible, genuine mesh assets. Run: node blender/generate-models.mjs
import * as T from 'three';
import {GLTFExporter} from 'three/examples/jsm/exporters/GLTFExporter.js';
import {RoundedBoxGeometry} from 'three/examples/jsm/geometries/RoundedBoxGeometry.js';
import {TextGeometry} from 'three/examples/jsm/geometries/TextGeometry.js';
import {FontLoader} from 'three/examples/jsm/loaders/FontLoader.js';
import fs from 'node:fs';
globalThis.FileReader=class{readAsArrayBuffer(b){b.arrayBuffer().then(x=>{this.result=x;this.onloadend?.()})}readAsDataURL(b){b.arrayBuffer().then(x=>{this.result='data:application/octet-stream;base64,'+Buffer.from(x).toString('base64');this.onloadend?.()})}};
const out='public/models';fs.mkdirSync(out,{recursive:true});
const black=new T.MeshPhysicalMaterial({color:'#25251f',metalness:.88,roughness:.23,clearcoat:1,clearcoatRoughness:.18});black.name='Obsidian';const gold=new T.MeshStandardMaterial({color:'#f2c94c',metalness:.8,roughness:.26});gold.name='UNDA_Gold';
function ribbon(segments,radial){const group=new T.Group();for(let part=0;part<3;part++){const pos=[],uv=[],idx=[];const n=segments/3;for(let i=0;i<=n;i++){const u=(part*n+i)/segments*Math.PI*2;const r=1.32+.19*Math.cos(3*u);const c=new T.Vector3(r*Math.cos(u),1.18*Math.sin(u),.38*Math.sin(2*u));const radialV=new T.Vector3(Math.cos(u),Math.sin(u),0);const z=new T.Vector3(0,0,1);const twist=u+.55*Math.sin(u*2);const a=radialV.clone().multiplyScalar(Math.cos(twist)).addScaledVector(z,Math.sin(twist));const b=radialV.clone().multiplyScalar(-Math.sin(twist)).addScaledVector(z,Math.cos(twist));for(let j=0;j<=radial;j++){const v=j/radial*Math.PI*2;const p=c.clone().addScaledVector(a,.48*Math.cos(v)).addScaledVector(b,.072*Math.sin(v));pos.push(...p);uv.push((part*n+i)/segments,j/radial);if(i<n&&j<radial){let k=i*(radial+1)+j;idx.push(k,k+1,k+radial+1,k+1,k+radial+2,k+radial+1)}}}const g=new T.BufferGeometry();g.setAttribute('position',new T.Float32BufferAttribute(pos,3));g.setAttribute('uv',new T.Float32BufferAttribute(uv,2));g.setIndex(idx);g.computeVertexNormals();const m=new T.Mesh(g,black);m.name='Ribbon_'+part;group.add(m)}const curve=new class extends T.Curve{getPoint(t){const u=t*Math.PI*2;const r=1.32+.19*Math.cos(3*u),twist=u+.55*Math.sin(u*2);return new T.Vector3(r*Math.cos(u)+.48*Math.cos(u)*Math.cos(twist),1.18*Math.sin(u)+.48*Math.sin(u)*Math.cos(twist),.38*Math.sin(2*u)+.48*Math.sin(twist))}};const seam=new T.Mesh(new T.TubeGeometry(curve,segments,.009,6,true),gold);seam.name='Gold_Seam';group.add(seam);return group;}
async function save(name,obj){const b=await new GLTFExporter().parseAsync(obj,{binary:true});fs.writeFileSync(out+'/'+name+'.glb',Buffer.from(b));console.log(name,Math.round(b.byteLength/1024)+' KB')}
await save('unda-sculpture',ribbon(240,24));await save('unda-sculpture-mobile',ribbon(120,12));await save('unda-sculpture-master',ribbon(600,64));
function device(w,h,d,r){const g=new T.Group();const body=new T.Mesh(new RoundedBoxGeometry(w,h,d,4,r),black);body.name='Body';g.add(body);const screen=new T.Mesh(new T.PlaneGeometry(w-.12,h-.12),new T.MeshStandardMaterial({color:'white',roughness:.8}));screen.name='Screen';screen.position.z=d/2+.004;g.add(screen);return g;}
const display=device(4.4,2.75,.13,.07);await save('display',display);const mobile=device(1.12,2.3,.12,.13);const lens=new T.Mesh(new T.CylinderGeometry(.027,.027,.014,16),black);lens.rotation.x=Math.PI/2;lens.position.set(0,1.07,.076);mobile.add(lens);await save('mobile',mobile);
const font=new FontLoader().parse(JSON.parse(fs.readFileSync('blender/helvetiker_bold.typeface.json','utf8')));const type=new T.Mesh(new TextGeometry('UNDA.',{font,size:.7,depth:.16,curveSegments:8,bevelEnabled:true,bevelThickness:.015,bevelSize:.01,bevelSegments:3}),black);type.geometry.center();await save('unda-type',type);
